
platform :ios, '14.0'
inhibit_all_warnings!
use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'

target 'Daleel' do

pod 'MBProgressHUD'
pod 'AFNetworking'
pod 'SDWebImage'
pod 'Masonry'
#明杰刷新 数据模型转换解析
pod 'MJRefresh'
pod 'MJExtension'
#图片选择处理
#pod 'TZImagePickerController'
#键盘处理
pod 'IQKeyboardManager'
pod 'ReactiveObjC'
#google
pod 'GoogleSignIn', '~>6.2.4'

pod 'Firebase/Analytics'
pod 'FirebaseCrashlytics'
pod 'Firebase/Messaging'

#Facebook
#pod 'FBSDKShareKit'
#pod 'FBSDKLoginKit'
# mob Share 三方登录 统计
pod 'mob_sharesdk', '~>4.4.6'
pod 'mob_sharesdk/ShareSDKPlatforms/Apple'
pod 'mob_sharesdk/ShareSDKPlatforms/Facebook'
pod 'mob_sharesdk/ShareSDKPlatforms/WhatsApp'
pod 'mob_sharesdk/ShareSDKPlatforms/SnapChat'
pod 'mob_sharesdk/ShareSDKPlatforms/Messenger'
pod 'mob_sharesdk/ShareSDKPlatforms/Instagram'
pod 'mob_sharesdk/ShareSDKPlatforms/Twitter'
pod 'BRPickerView'

pod 'metamask-ios-sdk'

end

post_install do |installer|

  installer.aggregate_targets.each do |target|

    target.xcconfigs.each do |variant, xcconfig|

      xcconfig_path = target.client_root + target.xcconfig_relative_path(variant)

      IO.write(xcconfig_path, IO.read(xcconfig_path).gsub("DT_TOOLCHAIN_DIR", "TOOLCHAIN_DIR"))

    end

  end

  installer.pods_project.targets.each do |target|

    target.build_configurations.each do |config|

      if config.base_configuration_reference.is_a? Xcodeproj::Project::Object::PBXFileReference

        xcconfig_path = config.base_configuration_reference.real_path

        IO.write(xcconfig_path, IO.read(xcconfig_path).gsub("DT_TOOLCHAIN_DIR", "TOOLCHAIN_DIR"))

      end

    end

  end

end
